### PR TITLE
Update community icons index.md

### PR DESCRIPTION
**Pull request by tu1h**
KubeSphere and Kubernetes are the opposite positions, correct them.

### CODE REVIEW

**Review by windsonsea — APPROVED** [review]
Thanks, the zh version has the same issue, could you handle it?

**Comment by tu1h** [comment]
> Thanks, the zh version has the same issue, could you handle it?

Can they in the same PR?

**Comment by windsonsea** [comment]
Sure, all right.

**Comment by tu1h** [comment]
done

**Review by windsonsea — APPROVED** [review]
Thanks

**Pull request merged**
